sql_create_community = """
    CREATE table COMMUNITY(
		COMM_NAME CHAR(255) NOT NULL PRIMARY KEY,
		COMM_AREA CHAR(255),
		COMM_HOUSEHOLDS CHAR(255),
		COMM_PLOT_RATIO CHAR(255),
		COMM_PARKING_NUM CHAR(255),
		COMM_GREEN_RATIO CHAR(255),
		COMM_PROPERTY_FEE CHAR(255)
    );
"""

sql_create_house = """
	CREATE table HOUSE(
		HOUSE_INDEX CHAR(255) NOT NULL PRIMARY KEY,
		TITLE VARCHAR(512),
		HOUSE_PRICE CHAR(255),
		HOUSE_INFO VARCHAR(1024),
		ADV VARCHAR(1024),
		DISADV VARCHAR(1024),
		CORE_POINT VARCHAR(1024),
		COMM_NAME CHAR(255),
		URL VARCHAR(1024),
		FOREIGN KEY (COMM_NAME) REFERENCES COMMUNITY(COMM_NAME)
    );
"""

sql_query_house = "SELECT * FROM `house`"

sql_query_community = "SELECT * FROM `community`"